package org.example.protushybrid.domain.core;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.example.protushybrid.service.admin.SyntheticDataGenerator;
import org.example.protushybrid.service.core.ClusterKeyUtil;

/**
 * FSLSM profile entity storing categorical cluster membership.
 *
 * <p><b>USAGE NOTE:</b> This entity is primarily used for <b>synthetic data generation</b>
 * via {@link SyntheticDataGenerator}.
 * Production recommendation flow computes cluster keys directly from {@link Learner}
 * style scores using {@link ClusterKeyUtil} without
 * persisting FslsmProfile entities.</p>
 *
 * <p>Maps to fslsm_profiles table with learner_id as PK.
 * Each field stores the dominant pole for one FSLSM dimension.</p>
 *
 * <p>The cluster_key is auto-generated by the database as:</p>
 * <pre>active_reflective || '_' || sensing_intuitive || '_' || visual_verbal || '_' || sequential_global</pre>
 *
 * <p>Example: "ACTIVE_SENSING_VISUAL_SEQUENTIAL"</p>
 *
 * @see SyntheticDataGenerator
 * @see ClusterKeyUtil
 */
@Entity
@Table(name = "fslsm_profiles", schema = "app")
@Getter
@Setter
public class FslsmProfile {

    @Id
    @Column(name = "learner_id")
    private Long learnerId;

    /**
     * Active-Reflective dimension: "ACTIVE" or "REFLECTIVE"
     */
    @Column(name = "active_reflective", nullable = false, length = 10)
    private String activeReflective;

    /**
     * Sensing-Intuitive dimension: "SENSING" or "INTUITIVE"
     */
    @Column(name = "sensing_intuitive", nullable = false, length = 10)
    private String sensingIntuitive;

    /**
     * Visual-Verbal dimension: "VISUAL" or "VERBAL"
     */
    @Column(name = "visual_verbal", nullable = false, length = 6)
    private String visualVerbal;

    /**
     * Sequential-Global dimension: "SEQUENTIAL" or "GLOBAL"
     */
    @Column(name = "sequential_global", nullable = false, length = 11)
    private String sequentialGlobal;

    /**
     * Computed cluster key (generated by database).
     * Format: "{ACTIVE|REFLECTIVE}_{SENSING|INTUITIVE}_{VISUAL|VERBAL}_{SEQUENTIAL|GLOBAL}"
     */
    @Column(name = "cluster_key", insertable = false, updatable = false, length = 64)
    private String clusterKey;

    /**
     * Create FslsmProfile from Learner's style scores.
     * Uses threshold logic: if |score| >= 0.6 (normalized), assign dominant pole.
     *
     * @param learner Learner with FSLSM scores in range [-11, +11]
     * @return FslsmProfile with categorical poles
     */
    public static FslsmProfile fromLearner(Learner learner) {
        FslsmProfile profile = new FslsmProfile();
        profile.setLearnerId(learner.getId());

        // Convert scores to categorical poles (positive = first pole, negative = second pole)
        profile.setActiveReflective(learner.getStyleActiveReflective() >= 0 ? "ACTIVE" : "REFLECTIVE");
        profile.setSensingIntuitive(learner.getStyleSensingIntuitive() >= 0 ? "SENSING" : "INTUITIVE");
        profile.setVisualVerbal(learner.getStyleVisualVerbal() >= 0 ? "VISUAL" : "VERBAL");
        profile.setSequentialGlobal(learner.getStyleSequentialGlobal() >= 0 ? "SEQUENTIAL" : "GLOBAL");

        return profile;
    }

    /**
     * Get cluster key manually (in case not yet persisted).
     * Database auto-generates this, but we compute it for convenience.
     */
    public String getOrComputeClusterKey() {
        if (clusterKey != null) {
            return clusterKey;
        }
        return String.format("%s_%s_%s_%s",
            activeReflective, sensingIntuitive, visualVerbal, sequentialGlobal);
    }

    @Override
    public String toString() {
        return String.format("FslsmProfile[learner=%d, cluster=%s]",
            learnerId, getOrComputeClusterKey());
    }
}
